### ISSUE TITLE
Thanks for your Qlora version Alpagasus

### ISSUE THREAD

**Issue by GPT4animal** [gauss5930/AlpaGasus2-QLoRA#1]
Great thanks to your effort on reproducing the Qlora version of my Alpagasus! It is a great repo! I will cite your repo on my original repo as well as ask the authors of Alpagasus to cite your repo on their webpage!

**Comment by gauss5930** [comment]
Thank you for your kind words about our repo! Also, thank you for the honor of being cited on the Alpagasus webpage! Thank you once again for such a great research!!
